version: 2
updates:
  - package-ecosystem: 'npm' # Also for Yarn
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
